DesignerProfile Update
LaFavela/favela pull request #51
Opened 2023-08-25 13:45 UTC by DzulhiRaihan

2023-08-25 14:13 UTC, VosMovok requested changes
Tombol like review masi belum berfungsi. Shadow tiap div card masi teralu tebel.
Btw Navbar km kemanain.

2023-08-25 14:15 UTC, DzulhiRaihan commented
Oke bang

2023-08-25 14:16 UTC, VosMovok requested changes

2023-08-25 14:16 UTC, VosMovok commented on src/pages/_app.tsx
Apa tujuannya ni??

2023-08-25 14:18 UTC, DzulhiRaihan commented on src/pages/_app.tsx
Salah commit bg sy cuman komen biar navbarnya ga ketampil, sellain itu gaada yg berubah

2023-08-26 05:54 UTC, VosMovok approved these changes

2023-08-26 05:56 UTC, merged